apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-api-server-deployment
  labels:
    app: api-server
spec:
  replicas: 3
  selector:
    matchLabels:
      app: api-server
  template:
    metadata:
      labels:
        app: api-server
    spec:
      containers:
      - name: http-api-server-container
        image: neajmorshad/http-api-server:0.0.2
        ports:
        - containerPort: 8080