apiVersion: v1
kind: Service
metadata:
  name: http-api-server-service
spec:
  type: NodePort
  selector:
    app: api-server
  ports:
    - protocol: TCP
      port: 8080 # service's port
      targetPort: 8080 # pod's port
      nodePort: 30000